### ISSUE TITLE
Print Bib Records with Firefox

### ISSUE THREAD

**Issue by CamilleGh** [ExLibrisGroup/print-bib-record#18]
Dear Ori,
In Firefox, both on Windows 10 and Mac OS (High Sierra), the Print bib record app doesn't seem to work.: the new window doesn't open after clicking "Print Records". I tried when running Firefox in Safe Mode.
In Safari, with MacOS High Sierra, it doesn't work either. The list of titles does not appear in the App window.
But our problem is mostly with Firefox.

Can you please help us ?
Thank you
Kind regards
Camille

https://user-images.githubusercontent.com/38520365/130728661-402792d7-03e2-4ee2-b828-3f3a7f550461.mp4

**Comment by ori229** [comment]
Better late than never...
Please try to uncheck "Block pop-up windows" in the Browser's settings - this should help.
