### ISSUE TITLE
Save multiple xml file ?

### ISSUE THREAD

**Issue by CamilleGh** [ExLibrisGroup/print-bib-record#7]
Dear Ori,
I've already posted this morning the question on developer center but I don't know where is the best place so I do it again here.

Is it possible to save multiple xml file in the cloud app ?
We are in the process of creating different templates for different types of documents and/or languages, and would like to be able to save them locally. For the moment, it is only possible to save one at a time.
Thank you for your help.
Kind regards
Camille

**Comment by ori229** [comment]
Replied in https://developers.exlibrisgroup.com/forums/topic/print-bib-records/
Currently, the App supports one custom XSL. 
See https://developers.exlibrisgroup.com/blog/how-to-make-a-custom-format-in-the-print-bib-records-cloud-app/
If you have XSLs you wrote which can be useful to others, please send me and I'll add them to the official App.
